package:
  name: pdbfixer
  version: 1.5

build:
  entry_points:
    - pdbfixer = pdbfixer.pdbfixer:main

requirements:
  build:
    - python
    - setuptools
    - openmm
    - numpy

  run:
    - python
    - openmm
    - numpy

test:
  requires:
    - nose

  imports:
    - pdbfixer

about:
  home: http://github.com/pandegroup/pdbfixer
  license: https://github.com/pandegroup/pdbfixer/blob/master/LICENSE
  summary: This is a copy of PDBFixer (http://github.com/pandegroup/pdbfixer) to be installed with Python 3.7.
